### ISSUE TITLE
flathub verification?

### ISSUE THREAD

**Issue by qoijjj** [flathub/com.github.geigi.cozy#13]
Getting verification would allow an increased level of user trust.

https://docs.flathub.org/docs/for-app-authors/verification#im-publishing-an-app-on-flathub-how-do-i-get-it-verified

Usually this requires the blessing of the original via hosting a file, but seeing as @geigi is maintaining both the source code and the flatpak, that makes this even easier :smile:

**Comment by geigi** [comment]
Forgot to mention it here but verification is completed :)
