### ISSUE TITLE
Runtime v41 slowly approaching its EOL

### ISSUE THREAD

**Issue by sophie-h** [flathub/com.github.geigi.cozy#7]
Maybe it can be replaced with 42 already.

Version 43 should be available on 21. of this month.

**Comment by CuriousApe2020** [comment]
It now is deprecated!

**Comment by troiganto** [comment]
Any updates on this? I just got a warning on my system that Cozy uses an EOL runtime. According to https://github.com/geigi/cozy/issues/741 the changes have already been made and just need to be pushed to Flathub.

**Comment by geigi** [comment]
Update will be available in the next few hours :)

**Comment by troiganto** [comment]
Thank you for the speedy response!
